<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ZHANG Fulin">
<meta name="dcterms.date" content="2024-04-03">

<title>Venture Capital Funding</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="VC_prediction_files/libs/clipboard/clipboard.min.js"></script>
<script src="VC_prediction_files/libs/quarto-html/quarto.js"></script>
<script src="VC_prediction_files/libs/quarto-html/popper.min.js"></script>
<script src="VC_prediction_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="VC_prediction_files/libs/quarto-html/anchor.min.js"></script>
<link href="VC_prediction_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="VC_prediction_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="VC_prediction_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="VC_prediction_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="VC_prediction_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="VC_prediction_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="VC_prediction_files/libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="VC_prediction_files/libs/datatables-binding-0.32/datatables.js"></script>
<script src="VC_prediction_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="VC_prediction_files/libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="VC_prediction_files/libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="VC_prediction_files/libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="VC_prediction_files/libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="VC_prediction_files/libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#import-packages" id="toc-import-packages" class="nav-link active" data-scroll-target="#import-packages"><span class="header-section-number">1</span> Import Packages</a></li>
  <li><a href="#description-of-the-dataset" id="toc-description-of-the-dataset" class="nav-link" data-scroll-target="#description-of-the-dataset"><span class="header-section-number">2</span> Description of the dataset</a></li>
  <li><a href="#eda" id="toc-eda" class="nav-link" data-scroll-target="#eda"><span class="header-section-number">3</span> EDA</a>
  <ul class="collapse">
  <li><a href="#univariate-analysis" id="toc-univariate-analysis" class="nav-link" data-scroll-target="#univariate-analysis"><span class="header-section-number">3.1</span> Univariate Analysis</a></li>
  <li><a href="#bivariate-analysis" id="toc-bivariate-analysis" class="nav-link" data-scroll-target="#bivariate-analysis"><span class="header-section-number">3.2</span> Bivariate Analysis</a></li>
  </ul></li>
  <li><a href="#modeling" id="toc-modeling" class="nav-link" data-scroll-target="#modeling"><span class="header-section-number">4</span> Modeling</a></li>
  <li><a href="#thinking-of-datalackagebeta-version" id="toc-thinking-of-datalackagebeta-version" class="nav-link" data-scroll-target="#thinking-of-datalackagebeta-version"><span class="header-section-number">5</span> Thinking of datalackage(Beta version)</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Venture Capital Funding</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">ZHANG Fulin </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            EM-Lyon Business School
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 3, 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Abstract</div>
    <p>This project focuses on a classification problem with the objective of predicting whether a company received venture capital (VC) funding in the year 2000. It presents a unique challenge that combines the application of data science and machine learning methodologies with an in-depth exploration of investment patterns and business growth dynamics. We will utilize a dataset featuring several variables, including the company identifier (firmcode), company age (Age), country of operation (Country), industry sector (Industry), and a range of financial metrics related to company size and performance (such as the natural logarithm of sales revenue, number of employees, and total assets). Additionally, the dataset contains a special variable (VCinv), which represents the frequency of VC investments in the company’s country and industry from 1996 to 2005 and will be used as an instrumental variable for VC in Heckman models. <br><br><br></p>
  </div>
</div>

</header>

<section id="import-packages" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Import Packages</h1>
<p>Import the necessary libraries</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)         </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)          </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DataExplorer)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastDummies)      </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)           </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)        </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lightgbm)      </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Metrics)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROSE)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s load the dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"VC_data.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="description-of-the-dataset" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Description of the dataset</h1>
<p>Let’s take a brief look on the data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(VCdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2610   24</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>(VCdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "age"         "country"     "firmcode"    "industry"    "logassets"  
 [6] "logassets_1" "logassets_2" "logassets_3" "logassets_4" "logassets_5"
[11] "logemp"      "logemp_1"    "logemp_2"    "logemp_3"    "logemp_4"   
[16] "logemp_5"    "logsales"    "logsales_1"  "logsales_2"  "logsales_3" 
[21] "logsales_4"  "logsales_5"  "VC"          "VCinv"      </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(VCdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,610
Columns: 24
$ firmcode    &lt;chr&gt; "1123", "3455", "2210", "6454", "3449", "1433", "3842", "7…
$ VC          &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ age         &lt;dbl&gt; 3, 0, 3, 4, 0, 4, 0, 12, 5, 11, 0, 7, 0, 7, 3, 5, 15, 0, 0…
$ country     &lt;chr&gt; "FINLAND", "GERMANY", "FRANCE", "SPAIN", "GERMANY", "FINLA…
$ industry    &lt;chr&gt; "Software", "Biotech", "Other R&amp;D", "ICT manufacturing", "…
$ VCinv       &lt;dbl&gt; 0.004594963, 0.027428571, 0.001359065, 0.001767230, 0.0069…
$ logsales    &lt;dbl&gt; 4.619535, 0.000000, 4.906051, 7.249131, 0.000000, 4.505667…
$ logemp      &lt;dbl&gt; 0.6931472, 0.0000000, 1.6094379, 2.5649493, 0.0000000, 0.6…
$ logassets   &lt;dbl&gt; 4.796612, 0.000000, 4.079435, 6.588883, 0.000000, 3.581796…
$ logemp_1    &lt;dbl&gt; 0.6931472, 1.6094379, 1.6094379, 2.7725887, 2.7725887, 0.6…
$ logemp_2    &lt;dbl&gt; 0.6931472, 1.6094379, NA, 3.1354942, 3.2580965, 0.6931472,…
$ logemp_3    &lt;dbl&gt; 0.6931472, 2.4849067, 1.3862944, 3.0445225, 3.2580965, 0.6…
$ logemp_4    &lt;dbl&gt; 0.6931472, 2.4849067, 1.3862944, 3.1780539, 3.2580965, NA,…
$ logemp_5    &lt;dbl&gt; 0.6931472, 3.4011974, 1.3862944, 3.4011974, 3.1780539, NA,…
$ logsales_1  &lt;dbl&gt; 4.215877, 5.748874, 5.097703, 7.439082, 7.926267, 4.557057…
$ logsales_2  &lt;dbl&gt; 4.714251, NA, 4.750316, 7.535911, 7.266609, 4.852439, NA, …
$ logsales_3  &lt;dbl&gt; 4.698802, 7.394920, 5.146444, 7.615391, 8.251705, 4.190956…
$ logsales_4  &lt;dbl&gt; 4.529790, 7.651690, 5.048716, 7.788105, 8.731167, NA, 7.12…
$ logsales_5  &lt;dbl&gt; 4.706643, 8.604625, 5.092274, 7.994081, 8.572102, NA, NA, …
$ logassets_1 &lt;dbl&gt; 4.662480, NA, 4.251836, 6.852866, NA, 3.552675, NA, 7.8095…
$ logassets_2 &lt;dbl&gt; 4.899704, NA, 4.204111, 6.988987, NA, 3.745209, NA, 8.0076…
$ logassets_3 &lt;dbl&gt; 4.845005, NA, 4.427922, 7.190490, NA, 3.599880, NA, 8.0795…
$ logassets_4 &lt;dbl&gt; 4.680842, NA, 4.227416, 7.376255, NA, NA, NA, 8.047971, 7.…
$ logassets_5 &lt;dbl&gt; 4.7510977, NA, 4.2364635, 7.5408087, NA, NA, NA, 8.2059126…</code></pre>
</div>
</div>
<p>The VCdata dataset contains <strong>23 features</strong>, and <strong>1 target value</strong>. There are a total of <strong>2610 observations</strong>. There are 3 string variables in the features and the rest are all type of <strong>double</strong>. The target value is a double but will be treated as a 2-categorical variable considering that it is a binary problem.</p>
<p>Here are the top and bottom 5 rows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(VCdata, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 24
  firmcode    VC   age country industry          VCinv logsales logemp logassets
  &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
1 1123         0     3 FINLAND Software        0.00459     4.62  0.693      4.80
2 3455         1     0 GERMANY Biotech         0.0274      0     0          0   
3 2210         0     3 FRANCE  Other R&amp;D       0.00136     4.91  1.61       4.08
4 6454         0     4 SPAIN   ICT manufactur… 0.00177     7.25  2.56       6.59
5 3449         1     0 GERMANY Software        0.00696     0     0          0   
# ℹ 15 more variables: logemp_1 &lt;dbl&gt;, logemp_2 &lt;dbl&gt;, logemp_3 &lt;dbl&gt;,
#   logemp_4 &lt;dbl&gt;, logemp_5 &lt;dbl&gt;, logsales_1 &lt;dbl&gt;, logsales_2 &lt;dbl&gt;,
#   logsales_3 &lt;dbl&gt;, logsales_4 &lt;dbl&gt;, logsales_5 &lt;dbl&gt;, logassets_1 &lt;dbl&gt;,
#   logassets_2 &lt;dbl&gt;, logassets_3 &lt;dbl&gt;, logassets_4 &lt;dbl&gt;, logassets_5 &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(VCdata, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 24
  firmcode    VC   age country industry          VCinv logsales logemp logassets
  &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
1 4699         0     0 GERMANY Software        0.00696     0      0         0   
2 2333         0     4 FRANCE  Other R&amp;D       0.00136     7.29   2.48      6.74
3 7761         0     7 UK      Software        0.00314     7.57   3.04      6.25
4 7794         0    10 UK      Software        0.00314     7.23   2.30      6.95
5 6033         0     9 SPAIN   ICT manufactur… 0.00177     6.72   1.61      6.46
# ℹ 15 more variables: logemp_1 &lt;dbl&gt;, logemp_2 &lt;dbl&gt;, logemp_3 &lt;dbl&gt;,
#   logemp_4 &lt;dbl&gt;, logemp_5 &lt;dbl&gt;, logsales_1 &lt;dbl&gt;, logsales_2 &lt;dbl&gt;,
#   logsales_3 &lt;dbl&gt;, logsales_4 &lt;dbl&gt;, logsales_5 &lt;dbl&gt;, logassets_1 &lt;dbl&gt;,
#   logassets_2 &lt;dbl&gt;, logassets_3 &lt;dbl&gt;, logassets_4 &lt;dbl&gt;, logassets_5 &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Let’s check the missing value in total</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"Nbr of missing value in total: %f"</span>,<span class="fu">sum</span>(<span class="fu">is.na</span>(VCdata)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Nbr of missing value in total: 6239.000000"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_missing</span>(VCdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="VC_prediction_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Contains 6239 null values distributed in different rows and columns. Compared to 2610 observations, that’s an average of 3 per row, so I can’t perform a simple delete operation, huge amounts of information would be lost.</p>
<p>Then briefly check the target values’ distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"The nbr of observations of VC = 1: %f"</span>, <span class="fu">count</span>(VCdata[VCdata<span class="sc">$</span>VC <span class="sc">==</span> <span class="st">'1'</span>, ]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The nbr of observations of VC = 1: 71.000000"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"The nbr of observations of VC = 0: %f"</span>, <span class="fu">count</span>(VCdata[VCdata<span class="sc">$</span>VC <span class="sc">==</span> <span class="st">'0'</span>, ]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The nbr of observations of VC = 0: 2539.000000"</code></pre>
</div>
</div>
<p>The results show that the ratio of the two categories of data for the target value is 71:2539, making the data extremely unbalanced.</p>
</section>
<section id="eda" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> EDA</h1>
<p>In this part, I am going to further explorer the features.</p>
<section id="univariate-analysis" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="univariate-analysis"><span class="header-section-number">3.1</span> Univariate Analysis</h2>
<p>Firstly, let’s take a look of the summary of all features.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(VCdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   firmcode               VC              age           country         
 Length:2610        Min.   :0.0000   Min.   : 0.000   Length:2610       
 Class :character   1st Qu.:0.0000   1st Qu.: 0.000   Class :character  
 Mode  :character   Median :0.0000   Median : 4.000   Mode  :character  
                    Mean   :0.0272   Mean   : 4.954                     
                    3rd Qu.:0.0000   3rd Qu.: 9.000                     
                    Max.   :1.0000   Max.   :15.000                     
                                                                        
   industry             VCinv             logsales          logemp     
 Length:2610        Min.   :0.000000   Min.   : 0.000   Min.   :0.000  
 Class :character   1st Qu.:0.003136   1st Qu.: 0.000   1st Qu.:0.000  
 Mode  :character   Median :0.005464   Median : 5.755   Median :1.609  
                    Mean   :0.006544   Mean   : 5.072   Mean   :1.819  
                    3rd Qu.:0.007952   3rd Qu.: 7.632   3rd Qu.:2.944  
                    Max.   :0.047059   Max.   :14.923   Max.   :8.537  
                                                                       
   logassets         logemp_1        logemp_2        logemp_3    
 Min.   : 0.000   Min.   :0.000   Min.   :0.000   Min.   :0.000  
 1st Qu.: 0.000   1st Qu.:1.099   1st Qu.:1.386   1st Qu.:1.386  
 Median : 5.424   Median :2.197   Median :2.303   Median :2.303  
 Mean   : 4.835   Mean   :2.445   Mean   :2.508   Mean   :2.510  
 3rd Qu.: 7.328   3rd Qu.:3.367   3rd Qu.:3.466   3rd Qu.:3.434  
 Max.   :14.215   Max.   :9.237   Max.   :9.443   Max.   :9.225  
                  NA's   :363     NA's   :384     NA's   :409    
    logemp_4        logemp_5       logsales_1       logsales_2    
 Min.   :0.000   Min.   :0.000   Min.   : 0.000   Min.   : 0.000  
 1st Qu.:1.099   1st Qu.:1.099   1st Qu.: 5.278   1st Qu.: 5.439  
 Median :2.197   Median :2.197   Median : 6.619   Median : 6.767  
 Mean   :2.400   Mean   :2.391   Mean   : 6.780   Mean   : 6.920  
 3rd Qu.:3.332   3rd Qu.:3.296   3rd Qu.: 8.114   3rd Qu.: 8.243  
 Max.   :9.183   Max.   :9.187   Max.   :15.074   Max.   :15.086  
 NA's   :547     NA's   :701     NA's   :277      NA's   :335     
   logsales_3       logsales_4       logsales_5      logassets_1    
 Min.   : 0.000   Min.   : 0.000   Min.   : 0.000   Min.   : 0.000  
 1st Qu.: 5.420   1st Qu.: 5.348   1st Qu.: 5.346   1st Qu.: 5.035  
 Median : 6.760   Median : 6.707   Median : 6.723   Median : 6.468  
 Mean   : 6.847   Mean   : 6.761   Mean   : 6.763   Mean   : 6.614  
 3rd Qu.: 8.158   3rd Qu.: 8.090   3rd Qu.: 8.077   3rd Qu.: 8.086  
 Max.   :14.948   Max.   :15.104   Max.   :15.083   Max.   :15.763  
 NA's   :338      NA's   :451      NA's   :530      NA's   :301     
  logassets_2      logassets_3      logassets_4      logassets_5    
 Min.   : 0.000   Min.   : 0.000   Min.   : 0.000   Min.   : 0.000  
 1st Qu.: 5.180   1st Qu.: 5.123   1st Qu.: 5.104   1st Qu.: 5.121  
 Median : 6.564   Median : 6.519   Median : 6.482   Median : 6.527  
 Mean   : 6.683   Mean   : 6.619   Mean   : 6.534   Mean   : 6.536  
 3rd Qu.: 8.077   3rd Qu.: 8.071   3rd Qu.: 7.969   3rd Qu.: 7.909  
 Max.   :15.691   Max.   :15.453   Max.   :14.455   Max.   :14.490  
 NA's   :337      NA's   :331      NA's   :436      NA's   :499     </code></pre>
</div>
</div>
<p>Firmcode are the IDs which are meaningless, so drop it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>VCdata <span class="ot">&lt;-</span> VCdata <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>firmcode)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="categirical-variables" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="categirical-variables"><span class="header-section-number">3.1.1</span> Categirical variables</h3>
<p>To find out the distribution of the categorical variables, I define a function to plot the population’s distribution and percent distribution as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>plot_categorical <span class="ot">&lt;-</span> <span class="cf">function</span>(data, column_name) {</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  data_summary <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(<span class="sc">!!</span><span class="fu">sym</span>(column_name)) <span class="sc">%&gt;%</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">Count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Percent =</span> Count <span class="sc">/</span> <span class="fu">sum</span>(Count) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data_summary, <span class="fu">aes_string</span>(<span class="at">x =</span> column_name, <span class="at">y =</span> <span class="st">"Count"</span>)) <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Count Distribution of"</span>, column_name), <span class="at">x =</span> column_name, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data_summary, <span class="fu">aes_string</span>(<span class="at">x =</span> column_name, <span class="at">y =</span> <span class="st">"Percent"</span>)) <span class="sc">+</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Percent Distribution of"</span>, column_name), <span class="at">x =</span> column_name, <span class="at">y =</span> <span class="st">"Percent"</span>)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">grid.arrange</span>(p1, p2, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Distribution of firms’ age</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(VCdata<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  3  0  4 12  5 11  7 15  8  2  6 13  9  1 10 14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(VCdata<span class="sc">$</span>age))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_categorical</span>(VCdata, <span class="st">"age"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="VC_prediction_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>Here, even though age is a continuous variable, it is a discrete variable, so here I chose to view the distribution in a bar chart. According to the image, there are more than 600 companies with age 0, which is more than a quarter of the total dataset.</p>
<ul>
<li>Distribution of country</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_categorical</span>(VCdata, <span class="st">"country"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="VC_prediction_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>The UK’s accounted for more than a quarter of the total, France’s for nearly 20%, and the others for about 10% each, and mainly in Western Europe.</p>
<ul>
<li>Distribution of industry</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_categorical</span>(VCdata, <span class="st">"industry"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="VC_prediction_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>Depends on the distribution of the type of industry, the grapes show that software accounted for for than 40% of the total, manufacturing for nearly 20%. All the others are around 5%, with Aerospace being the least.</p>
</section>
<section id="quantitative-variables" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="quantitative-variables"><span class="header-section-number">3.1.2</span> Quantitative variables</h3>
<p>Define a function to show box-plot and violin-plot in order to show the distribution of quantitative variables</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>plot_quantitative <span class="ot">&lt;-</span> <span class="cf">function</span>(data, column_name) {</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  box_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="sc">!!</span><span class="fu">sym</span>(column_name))) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Box plot of"</span>, column_name), <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> column_name)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  violin_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="sc">!!</span><span class="fu">sym</span>(column_name))) <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_violin</span>(<span class="at">trim =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Violin Plot of"</span>, column_name), <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> column_name)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">grid.arrange</span>(box_plot, violin_plot, <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Distribution of VCinv</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_quantitative</span>(VCdata, <span class="st">"VCinv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="VC_prediction_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The overall investment frequency is mainly distributed around 0.005 ± 0.0025 and there are a lot of outliers mainly in the interval 0.015-0.05.</p>
<p>So I wanted to take a more visual look at these discrete values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>VCinv0015 <span class="ot">&lt;-</span> VCdata <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(VCinv <span class="sc">&gt;</span> <span class="fl">0.015</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(VCinv0015)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 98 × 23
      VC   age country industry  VCinv logsales logemp logassets logemp_1
   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1     1     0 GERMANY Biotech  0.0274     0      0         0       1.61 
 2     0     2 ITALY   TLC      0.0248     6.12   2.94      6.29    2.71 
 3     0     4 SPAIN   Biotech  0.0183     5.47   1.39      5.41    1.39 
 4     0     0 GERMANY Biotech  0.0274     0      0         0       1.79 
 5     0     5 ITALY   TLC      0.0248     7.74   3.04      6.73    3.04 
 6     1     0 ITALY   TLC      0.0248     0      0         0       2.08 
 7     0     0 GERMANY Biotech  0.0274     0      0         0       1.10 
 8     0     0 GERMANY Biotech  0.0274     0      0         0      NA    
 9     0     0 GERMANY Biotech  0.0274     0      0         0      NA    
10     1     0 GERMANY Biotech  0.0274     0      0         0       0.693
# ℹ 88 more rows
# ℹ 14 more variables: logemp_2 &lt;dbl&gt;, logemp_3 &lt;dbl&gt;, logemp_4 &lt;dbl&gt;,
#   logemp_5 &lt;dbl&gt;, logsales_1 &lt;dbl&gt;, logsales_2 &lt;dbl&gt;, logsales_3 &lt;dbl&gt;,
#   logsales_4 &lt;dbl&gt;, logsales_5 &lt;dbl&gt;, logassets_1 &lt;dbl&gt;, logassets_2 &lt;dbl&gt;,
#   logassets_3 &lt;dbl&gt;, logassets_4 &lt;dbl&gt;, logassets_5 &lt;dbl&gt;</code></pre>
</div>
</div>
<p>These discrete observations are mainly Biotech or Internet industries. What specific insights are available may require further research.</p>
</section>
</section>
<section id="bivariate-analysis" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="bivariate-analysis"><span class="header-section-number">3.2</span> Bivariate Analysis</h2>
<ul>
<li>Age vs VC</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(VCdata, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(VC), <span class="at">y =</span> age, <span class="at">fill =</span> <span class="fu">factor</span>(VC))) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"VC Received"</span>, <span class="at">y =</span> <span class="st">"Age"</span>, <span class="at">title =</span> <span class="st">"Distribution of Age by VC Status"</span>) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">"VC Status"</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="VC_prediction_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(VC <span class="sc">~</span> <span class="fu">factor</span>(age), <span class="at">data =</span> VCdata)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
factor(age)   15   1.59 0.10601   4.075 2.01e-07 ***
Residuals   2594  67.48 0.02601                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>According to the box plot demonstration, for the category of <code>VC=1</code>, there is a smaller trend relative to <code>VC=0</code>, which means that it may be possible for the public young firms to receive capital more instead. <strong>p-value of 2.01e-07</strong> was then obtained by using ANOVA analysis, which indicates that there is a significant difference between the age groups on the variable of receiving VC.</p>
<ul>
<li>Logxxxx vs VC</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>log_vars <span class="ot">&lt;-</span> <span class="fu">names</span>(VCdata)[<span class="fu">grepl</span>(<span class="st">"log"</span>, <span class="fu">names</span>(VCdata))]</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>plot_list <span class="ot">&lt;-</span> <span class="fu">lapply</span>(log_vars, <span class="cf">function</span>(var) {</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(VCdata, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(VC), <span class="at">y =</span> <span class="fu">get</span>(var), <span class="at">fill =</span> <span class="fu">factor</span>(VC))) <span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"VC Received"</span>, <span class="at">y =</span> var, <span class="at">title =</span> <span class="fu">paste</span>(var, <span class="st">"by VC Status"</span>)) <span class="sc">+</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_discrete</span>(<span class="at">name =</span> <span class="st">"VC Status"</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)) <span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>n_cols <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>n_rows <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(<span class="fu">length</span>(plot_list) <span class="sc">/</span> n_cols)</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(<span class="at">grobs =</span> plot_list, <span class="at">ncol =</span> n_cols, <span class="at">nrow =</span> n_rows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="VC_prediction_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>anova_results <span class="ot">&lt;-</span> <span class="fu">sapply</span>(log_vars, <span class="cf">function</span>(var) {</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="fu">reformulate</span>(var, <span class="at">response =</span> <span class="st">"VC"</span>), <span class="at">data =</span> VCdata)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(anova_result)[[<span class="dv">1</span>]][<span class="st">"Pr(&gt;F)"</span>][<span class="dv">1</span>, <span class="dv">1</span>]</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>anova_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Variable =</span> <span class="fu">names</span>(anova_results), <span class="at">P_Value =</span> <span class="fu">unlist</span>(anova_results))</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(anova_df) <span class="sc">%&gt;%</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatStyle</span>(</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'P_Value'</span>,</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">backgroundColor =</span> <span class="fu">styleInterval</span>(<span class="fl">0.05</span>, <span class="fu">c</span>(<span class="st">'lightgreen'</span>, <span class="st">'lightcoral'</span>))</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div class="datatables html-widget html-fill-item" id="htmlwidget-8bbc147c1848267840c6" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-8bbc147c1848267840c6">{"x":{"filter":"none","vertical":false,"data":[["logsales","logemp","logassets","logemp_1","logemp_2","logemp_3","logemp_4","logemp_5","logsales_1","logsales_2","logsales_3","logsales_4","logsales_5","logassets_1","logassets_2","logassets_3","logassets_4","logassets_5"],["logsales","logemp","logassets","logemp_1","logemp_2","logemp_3","logemp_4","logemp_5","logsales_1","logsales_2","logsales_3","logsales_4","logsales_5","logassets_1","logassets_2","logassets_3","logassets_4","logassets_5"],[1.629330362283388e-09,2.978735066517406e-05,3.851465657356458e-08,0.2008845406925075,0.000122887331001778,7.56628437154344e-05,0.0003149708272224765,0.0005895989262612096,0.5750591427930376,0.06459259606982808,0.01702388096921604,0.004291485744142298,0.00315747977714372,1.599338917172177e-06,1.62699215975189e-06,2.40516731758978e-06,1.599821368635539e-06,1.876096942042315e-05]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Variable<\/th>\n      <th>P_Value<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":2},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Variable","targets":1},{"name":"P_Value","targets":2}],"order":[],"autoWidth":false,"orderClasses":false,"rowCallback":"function(row, data, displayNum, displayIndex, dataIndex) {\nvar value=data[2]; $(this.api().cell(row, 2).node()).css({'background-color':isNaN(parseFloat(value)) ? '' : value <= 0.05 ? \"lightgreen\" : \"lightcoral\"});\n}"}},"evals":["options.rowCallback"],"jsHooks":[]}</script>
</div>
</div>
<p>Based on the distribution and the p-value after ANOVA analysis, I found that the vast majority of log-related FEATURES showed a significant difference between the two groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>log_data <span class="ot">&lt;-</span> VCdata[log_vars]</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(log_data, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">method =</span> <span class="st">"color"</span>, <span class="at">type =</span> <span class="st">"upper"</span>, <span class="at">order =</span> <span class="st">"hclust"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.col =</span> <span class="st">"black"</span>, <span class="at">tl.srt =</span> <span class="dv">45</span>, <span class="at">addCoef.col =</span> <span class="st">"white"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="VC_prediction_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="1440"></p>
</div>
</div>
<p>Here they are all positively correlated with each other, even strongly positively correlated, I actually did not find a reasonable explanation for this, the log was chosen to store this information in order to correct the original distribution that was skewed to the left into one that is easier to recognize, but if earnings, market capitalization, and number of employees are all increasing as the year changes, then there should be a 50/50 split between positive and negative correlation. Further research is needed here.</p>
<ul>
<li>Industry / Country vs VC</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>fisher_industry_vc <span class="ot">&lt;-</span> <span class="fu">fisher.test</span>(<span class="fu">table</span>(VCdata<span class="sc">$</span>industry, VCdata<span class="sc">$</span>VC), <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>fisher_country_vc <span class="ot">&lt;-</span> <span class="fu">fisher.test</span>(<span class="fu">table</span>(VCdata<span class="sc">$</span>country, VCdata<span class="sc">$</span>VC), <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fisher_industry_vc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data with simulated p-value (based on
    2000 replicates)

data:  table(VCdata$industry, VCdata$VC)
p-value = 0.0009995
alternative hypothesis: two.sided</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fisher_country_vc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data with simulated p-value (based on
    2000 replicates)

data:  table(VCdata$country, VCdata$VC)
p-value = 0.0004998
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mosaicplot</span>(<span class="fu">table</span>(VCdata<span class="sc">$</span>industry, VCdata<span class="sc">$</span>VC), <span class="at">main =</span> <span class="st">"Mosaic Plot of Industry and VC"</span>, <span class="at">color =</span> <span class="cn">TRUE</span>, <span class="at">las =</span> <span class="dv">2</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mosaicplot</span>(<span class="fu">table</span>(VCdata<span class="sc">$</span>country, VCdata<span class="sc">$</span>VC), <span class="at">main =</span> <span class="st">"Mosaic Plot of Country and VC"</span>, <span class="at">color =</span> <span class="cn">TRUE</span>, <span class="at">las =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="VC_prediction_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>Here the chi-square test was abandoned in favor of the Fischer test due to the extremely limited amount of data of certain types. Based on the p-value it was shown that there was indeed a significant difference in the distribution between the groups. Again, based on the mosaic plot it is easy to see that the <strong>Internet</strong> and <strong>TLC</strong> sectors have a higher percentage of investments, with <strong>Biotech</strong> coming in second. In terms of country orientation, <strong>Germany</strong> is the highest, followed by <strong>Italy</strong>. <strong>France</strong> has a relatively small share, albeit from a large base.</p>
</section>
</section>
<section id="modeling" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Modeling</h1>
<p>In this part, I am going to train the model, and here I chose lightgbm. The power for binary classification problems, the support for nulls, and the fast computational power were the main reasons for me to choose it.</p>
<p>So apply one-hot encoding on the categorical variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>categorical_columns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"country"</span>, <span class="st">"industry"</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>VCdata_encoded <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(VCdata, <span class="at">select_columns =</span> categorical_columns, <span class="at">remove_first_dummy =</span> <span class="cn">TRUE</span>, <span class="at">remove_selected_columns =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(VCdata_encoded) <span class="ot">&lt;-</span> <span class="fu">make.names</span>(<span class="fu">colnames</span>(VCdata_encoded), <span class="at">unique =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Take a look on the encoded data to make sure the process has been done correctly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(VCdata_encoded)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 36
     VC   age   VCinv logsales logemp logassets logemp_1 logemp_2 logemp_3
  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1     0     3 0.00459     4.62  0.693      4.80    0.693    0.693    0.693
2     1     0 0.0274      0     0          0       1.61     1.61     2.48 
3     0     3 0.00136     4.91  1.61       4.08    1.61    NA        1.39 
4     0     4 0.00177     7.25  2.56       6.59    2.77     3.14     3.04 
5     1     0 0.00696     0     0          0       2.77     3.26     3.26 
6     0     4 0.00459     4.51  0.693      3.58    0.693    0.693    0.693
# ℹ 27 more variables: logemp_4 &lt;dbl&gt;, logemp_5 &lt;dbl&gt;, logsales_1 &lt;dbl&gt;,
#   logsales_2 &lt;dbl&gt;, logsales_3 &lt;dbl&gt;, logsales_4 &lt;dbl&gt;, logsales_5 &lt;dbl&gt;,
#   logassets_1 &lt;dbl&gt;, logassets_2 &lt;dbl&gt;, logassets_3 &lt;dbl&gt;, logassets_4 &lt;dbl&gt;,
#   logassets_5 &lt;dbl&gt;, country_FINLAND &lt;int&gt;, country_FRANCE &lt;int&gt;,
#   country_GERMANY &lt;int&gt;, country_ITALY &lt;int&gt;, country_SPAIN &lt;int&gt;,
#   country_UK &lt;int&gt;, industry_Biotech &lt;int&gt;, industry_ICT.manufacturing &lt;int&gt;,
#   industry_Internet &lt;int&gt;, industry_Other.R.D &lt;int&gt;, …</code></pre>
</div>
</div>
<p>Next divide the train, validation, and test sets. The ratio is 8:1:1. Due to the extreme imbalance in the dataset, here I chose to use <strong>oversampling</strong> to address the imbalance. I also tried mixed sampling before this, but the accuracy of the predicted results was only 50%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">48</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>trainIndex <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(VCdata_encoded<span class="sc">$</span>VC, <span class="at">p =</span> .<span class="dv">8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>data_train <span class="ot">&lt;-</span> VCdata_encoded[trainIndex, ]</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>data_temp <span class="ot">&lt;-</span> VCdata_encoded[<span class="sc">-</span>trainIndex, ]</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>valIndex <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(data_temp<span class="sc">$</span>VC, <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>data_val <span class="ot">&lt;-</span> data_temp[valIndex, ]</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>data_test <span class="ot">&lt;-</span> data_temp[<span class="sc">-</span>valIndex, ]</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>data_train <span class="ot">&lt;-</span> <span class="fu">ovun.sample</span>(VC <span class="sc">~</span> ., <span class="at">data =</span> data_train, <span class="at">method =</span> <span class="st">"over"</span>, <span class="at">N =</span> <span class="fu">nrow</span>(data_train) <span class="sc">*</span> <span class="dv">2</span>)<span class="sc">$</span>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Initialize the model and set the parameters, after several attempts, the learning rate is better at 0.001, while setting the early stop parameter to prevent overfitting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>train_set <span class="ot">&lt;-</span> <span class="fu">lgb.Dataset</span>(<span class="at">data =</span> <span class="fu">as.matrix</span>(data_train[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(data_train) <span class="sc">==</span> <span class="st">"VC"</span>)]), <span class="at">label =</span> data_train<span class="sc">$</span>VC)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>val_set <span class="ot">&lt;-</span> <span class="fu">lgb.Dataset</span>(<span class="at">data =</span> <span class="fu">as.matrix</span>(data_val[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(data_val) <span class="sc">==</span> <span class="st">"VC"</span>)]), <span class="at">label =</span> data_val<span class="sc">$</span>VC)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>params <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">objective =</span> <span class="st">"binary"</span>,</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">metric =</span> <span class="st">"binary_logloss"</span>,</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">learning_rate =</span> <span class="fl">0.001</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>model_lgb <span class="ot">&lt;-</span> <span class="fu">lgb.train</span>(</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">params =</span> params,</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train_set,</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">valids =</span> <span class="fu">list</span>(<span class="at">validation =</span> val_set),</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">nrounds =</span> <span class="dv">100000</span>,</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">early_stopping_rounds =</span> <span class="dv">10</span>,</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbose =</span> <span class="dv">0</span></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf</code></pre>
</div>
</div>
<p><code>In order to prevent the html page from taking up too much space, I will temporarily set the verbose to 0. If you need to check it further, you can adjust its value to 1.</code></p>
<p>After 4341 iterations, the <strong>loss</strong> was reduced from 1.36246 to a minimum of 0.0794232.</p>
<p>Then look at the accuracy on the training and validation sets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>train_preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_lgb, <span class="fu">data.matrix</span>(data_train[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(data_train) <span class="sc">==</span> <span class="st">"VC"</span>)]), </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">num_iteration =</span> model_lgb<span class="sc">$</span>best_iter)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>val_preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_lgb, <span class="fu">data.matrix</span>(data_val[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(data_val) <span class="sc">==</span> <span class="st">"VC"</span>)]), </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">num_iteration =</span> model_lgb<span class="sc">$</span>best_iter)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>train_preds_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(train_preds <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>val_preds_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(val_preds <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>train_accuracy <span class="ot">&lt;-</span> <span class="fu">accuracy</span>(train_preds_class, data_train<span class="sc">$</span>VC)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>val_accuracy <span class="ot">&lt;-</span> <span class="fu">accuracy</span>(val_preds_class, data_val<span class="sc">$</span>VC)</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Training accuracy:"</span>, train_accuracy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Training accuracy: 1"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Validation accuracy:"</span>, val_accuracy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Validation accuracy: 0.980842911877395"</code></pre>
</div>
</div>
<p>The accuracy reached <strong>100%</strong> on the training set and <strong>98%</strong> on the validation set, with little difference and no overfitting.</p>
<p>Since the model performance is already good, grid searching and cross-validation are not performed here, and other operations such as further hyper-parameter tuning and improving generalization are not performed.</p>
<p>I then make predictions on a test set and print the accuracy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_lgb, <span class="fu">data.matrix</span>(data_test[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(data_test) <span class="sc">==</span> <span class="st">"VC"</span>)]))</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>predictions_binary <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predictions <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>test_accuracy <span class="ot">&lt;-</span> <span class="fu">accuracy</span>(data_test<span class="sc">$</span>VC, predictions_binary)</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Test accuracy:"</span>, test_accuracy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Test accuracy: 0.942528735632184"</code></pre>
</div>
</div>
<p>The accuracy on the test set is <strong>94.2%</strong>, indicating a high generalization capability and good performance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>conf_mat <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(predictions_binary), <span class="fu">as.factor</span>(data_test<span class="sc">$</span>VC))</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>recall <span class="ot">&lt;-</span> conf_mat<span class="sc">$</span>byClass[<span class="st">'Sensitivity'</span>]</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Recall:"</span>, recall))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Recall: 0.9800796812749"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>preds_vs_actual <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Predicted =</span> predictions_binary, <span class="at">Actual =</span> data_test<span class="sc">$</span>VC)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="co">#preds_vs_actual</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>actual_ones <span class="ot">&lt;-</span> preds_vs_actual <span class="sc">%&gt;%</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Actual <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="co">#actual_ones</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I also checked the recall rate here because the first time I used a combination of oversampling and not dealing with missing values (these two attempts are not reflected in the code part). To prevent the model from achieving high accuracy by blindly predicting the majority class, I further output the recall rate. Here, the recall rate reached <strong>98%</strong>, indicating that the prediction of the positive cases (the minority class, which, after oversampling, is no longer an absolute minority) is also precise. Additionally, I output a comparison table of predicted values and actual values. <code>I have commented it out here to prevent taking up too much space on the HTML page.</code></p>
<p>Then I looked at the feature importance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>importance <span class="ot">&lt;-</span> <span class="fu">lgb.importance</span>(model_lgb)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>importance_sorted <span class="ot">&lt;-</span> importance[<span class="fu">order</span>(<span class="sc">-</span>importance<span class="sc">$</span>Gain), ]</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(importance_sorted, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Feature, <span class="sc">-</span>Gain), <span class="at">y =</span> Gain)) <span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">'steelblue'</span>) <span class="sc">+</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Feature Importance"</span>, <span class="at">x =</span> <span class="st">"Features"</span>, <span class="at">y =</span> <span class="st">"Importance (Gain)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="VC_prediction_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on the feature importance, I found that <strong>logemp_3</strong> (the natural logarithm of the number of employees in 2002) and <strong>age</strong> made an unusually significant contribution to the prediction of VC. Industry and country did not seem to provide much help. Here, all the feature values did not differ by thousands, so no normalization or similar operations were performed.</p>
</section>
<section id="thinking-of-datalackagebeta-version" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Thinking of datalackage(Beta version)</h1>
<p>I’ve always harbored a concern, not just because the model’s accuracy is exceptionally high without any signs of overfitting, but also regarding the possibility of a misrepresentation in the feature descriptions provided in the problem statement. My concern arises from the definition of VC as a dummy variable equal to one if the company received VC in the year 2000. However, the variables logemp_1 to logemp_5, logsales_1 to logsales_5, and logassets_1 to logassets_5 represent the natural logarithms of the company’s number of employees, sales revenues, and total assets at the end of the year 2000 through to 2004 respectively. I am questioning whether using data from the year 2000 onwards could lead to data leakage, thus accounting for the model’s unusually high predictive accuracy. Alternatively, could there be an error in the problem statement’s explanation of VC? To address these concerns, I have decided to eliminate all data from the year 2000 onwards and to repeat the above processes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>log_vars_to_remove <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">"log.*_[1-5]"</span>, <span class="fu">names</span>(VCdata), <span class="at">value =</span> <span class="cn">TRUE</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>VCdata_1999 <span class="ot">&lt;-</span> VCdata[ , <span class="sc">!</span>(<span class="fu">names</span>(VCdata) <span class="sc">%in%</span> log_vars_to_remove)]</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(VCdata_1999)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
     VC   age country industry            VCinv logsales logemp logassets
  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;               &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
1     0     3 FINLAND Software          0.00459     4.62  0.693      4.80
2     1     0 GERMANY Biotech           0.0274      0     0          0   
3     0     3 FRANCE  Other R&amp;D         0.00136     4.91  1.61       4.08
4     0     4 SPAIN   ICT manufacturing 0.00177     7.25  2.56       6.59
5     1     0 GERMANY Software          0.00696     0     0          0   
6     0     4 FINLAND Software          0.00459     4.51  0.693      3.58</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>categorical_columns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"country"</span>, <span class="st">"industry"</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>VCdata_encoded <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(VCdata_1999, <span class="at">select_columns =</span> categorical_columns, <span class="at">remove_first_dummy =</span> <span class="cn">TRUE</span>, <span class="at">remove_selected_columns =</span> <span class="cn">TRUE</span>)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(VCdata_encoded) <span class="ot">&lt;-</span> <span class="fu">make.names</span>(<span class="fu">colnames</span>(VCdata_encoded), <span class="at">unique =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">48</span>)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>trainIndex <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(VCdata_encoded<span class="sc">$</span>VC, <span class="at">p =</span> .<span class="dv">8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>data_train <span class="ot">&lt;-</span> VCdata_encoded[trainIndex, ]</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>data_temp <span class="ot">&lt;-</span> VCdata_encoded[<span class="sc">-</span>trainIndex, ]</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>valIndex <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(data_temp<span class="sc">$</span>VC, <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>data_val <span class="ot">&lt;-</span> data_temp[valIndex, ]</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>data_test <span class="ot">&lt;-</span> data_temp[<span class="sc">-</span>valIndex, ]</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>data_train_balanced <span class="ot">&lt;-</span> <span class="fu">ovun.sample</span>(VC <span class="sc">~</span> ., <span class="at">data =</span> data_train, <span class="at">method =</span> <span class="st">"over"</span>, <span class="at">N =</span> <span class="fu">nrow</span>(data_train) <span class="sc">*</span> <span class="dv">2</span>)<span class="sc">$</span>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>train_set <span class="ot">&lt;-</span> <span class="fu">lgb.Dataset</span>(<span class="at">data =</span> <span class="fu">as.matrix</span>(data_train_balanced[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(data_train_balanced) <span class="sc">==</span> <span class="st">"VC"</span>)]), <span class="at">label =</span> data_train_balanced<span class="sc">$</span>VC)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>val_set <span class="ot">&lt;-</span> <span class="fu">lgb.Dataset</span>(<span class="at">data =</span> <span class="fu">as.matrix</span>(data_val[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(data_val) <span class="sc">==</span> <span class="st">"VC"</span>)]), <span class="at">label =</span> data_val<span class="sc">$</span>VC)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>params <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">objective =</span> <span class="st">"binary"</span>,</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">metric =</span> <span class="st">"binary_logloss"</span>,</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">learning_rate =</span> <span class="fl">0.001</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>model_lgb <span class="ot">&lt;-</span> <span class="fu">lgb.train</span>(</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">params =</span> params,</span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train_set,</span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">valids =</span> <span class="fu">list</span>(<span class="at">validation =</span> val_set),</span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">nrounds =</span> <span class="dv">100000</span>,</span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">early_stopping_rounds =</span> <span class="dv">10</span>,</span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">verbose =</span> <span class="dv">0</span></span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>train_preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_lgb, <span class="fu">data.matrix</span>(data_train_balanced[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(data_train_balanced) <span class="sc">==</span> <span class="st">"VC"</span>)]), </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">num_iteration =</span> model_lgb<span class="sc">$</span>best_iter)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>val_preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_lgb, <span class="fu">data.matrix</span>(data_val[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(data_val) <span class="sc">==</span> <span class="st">"VC"</span>)]), </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">num_iteration =</span> model_lgb<span class="sc">$</span>best_iter)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>train_preds_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(train_preds <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>val_preds_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(val_preds <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>train_accuracy <span class="ot">&lt;-</span> <span class="fu">accuracy</span>(train_preds_class, data_train_balanced<span class="sc">$</span>VC)</span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>val_accuracy <span class="ot">&lt;-</span> <span class="fu">accuracy</span>(val_preds_class, data_val<span class="sc">$</span>VC)</span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Training accuracy:"</span>, train_accuracy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Training accuracy: 0.925287356321839"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Validation accuracy:"</span>, val_accuracy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Validation accuracy: 0.842911877394636"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_lgb, <span class="fu">data.matrix</span>(data_test[,<span class="sc">-</span><span class="fu">which</span>(<span class="fu">names</span>(data_test) <span class="sc">==</span> <span class="st">"VC"</span>)]))</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>predictions_binary <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predictions <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>test_accuracy <span class="ot">&lt;-</span> <span class="fu">accuracy</span>(data_test<span class="sc">$</span>VC, predictions_binary)</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Test accuracy:"</span>, test_accuracy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Test accuracy: 0.823754789272031"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>conf_mat <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(predictions_binary), <span class="fu">as.factor</span>(data_test<span class="sc">$</span>VC))</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>recall <span class="ot">&lt;-</span> conf_mat<span class="sc">$</span>byClass[<span class="st">'Sensitivity'</span>]</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Recall:"</span>, recall))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Recall: 0.844621513944223"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>importance <span class="ot">&lt;-</span> <span class="fu">lgb.importance</span>(model_lgb)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>importance_sorted <span class="ot">&lt;-</span> importance[<span class="fu">order</span>(<span class="sc">-</span>importance<span class="sc">$</span>Gain), ]</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(importance_sorted, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Feature, <span class="sc">-</span>Gain), <span class="at">y =</span> Gain)) <span class="sc">+</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">'steelblue'</span>) <span class="sc">+</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Feature Importance"</span>, <span class="at">x =</span> <span class="st">"Features"</span>, <span class="at">y =</span> <span class="st">"Importance (Gain)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="VC_prediction_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The following points can be found here based on the results:</p>
<ul>
<li><p>“Training accuracy: 0.925287356321839”</p></li>
<li><p>“Validation accuracy: 0.842911877394636”</p></li>
<li><p>“Test accuracy: 0.823754789272031”</p></li>
<li><p>“Test Recall: 0.844621513944223”</p></li>
<li><p>Overall accuracy has decreased</p></li>
<li><p>The accuracy of the validation set has decreased compared to the training set, there may be over-fitting problems and the model has poor generalization ability.</p></li>
<li><p>According to the new feature importance, we can find that age is still the highest after missing logassets_1, which indicates that age does dominate some predictions, and logassets_1 and VC are highly correlated.</p></li>
<li><p>Next, we can try to find the best hyper-parameters by grid search and use cross-validation to enhance the model generalization ability and reduce over-fitting.</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>